---
services:
  telegram-immich-bot:
    container_name: telegram-immich-bot
    environment:
      - IMMICH_API_URL=
      - IMMICH_API_KEY=
      - TELEGRAM_BOT_TOKEN=
      - ALLOWED_USER_IDS=
      - TELEGRAM_API_URL=http://telegram-bot-api:8081/bot
      - TZ=America/Los_Angeles
    image: ghcr.io/rgr4y/telegram-immich-bot
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - telegram-bot-api

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    environment:
      - TELEGRAM_API_ID=
      - TELEGRAM_API_HASH=
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    restart: unless-stopped

volumes:
  telegram-bot-api-data:

