---
services:
  telegram-immich-bot:
    container_name: telegram-immich-bot
    environment:
      - IMMICH_API_URL=
      - IMMICH_API_KEY=
      - TELEGRAM_BOT_TOKEN=
      - ALLOWED_USER_IDS=
      - TZ=America/Los_Angeles
    image: ghcr.io/rgr4y/telegram-immich-bot
    build: .
